echo -e "┌──────────────────────────────────────┐"
echo -e "│         =   INFORMASI SERVER  =   │"
echo -e "└──────────────────────────────────────┘"
echo -e " OS SYSTEM            : "
echo -e " ISP                  : "
echo -e " REGION               : "
echo -e " IP                   : "
echo -e " DOMAIN               : "
echo -e " RAM                  : "
echo -e "┌──────────────────────────────────────┐"
echo -e "│   SSH :    VMESS :    VLESS :    TROJAN :   │"
echo -e "└──────────────────────────────────────┘"
echo -e "┌──────────────────────────────────────┐"
echo -e "│               = MENU UTAMA = │"
echo -e "└──────────────────────────────────────┘"
echo -e "  1. SSH MANAGER             5. BOT MANAGER    "
echo -e "  2. VMESS MANAGER           6. CHANGE DOMAIN"
echo -e "  3. VLESS MANAGER           7. RESTART SERV.  "
echo -e "  4. TROJAN MANAGER          8. REBOOT SERVER  "
echo -e "└──────────────────────────────────────┘"


